import { useState } from 'react';
import { Award, CheckCircle2, HelpCircle, Send } from 'lucide-react';

export default function DemoTest({ onAddLedgerEntry }) {
  const [selectedAnswers, setSelectedAnswers] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState(null);

  const questions = [
    {
      id: 1,
      question: "What is the minimum similarity threshold enforced by the air-gapped Plagiarism Shield?",
      options: ["Below 50%", "Below 70%", "Below 90%", "Zero tolerance"],
      correct: 1 // index for Below 70%
    },
    {
      id: 2,
      question: "How is the core escrow pool split according to Sylo AI governance rules?",
      options: [
        "Equal distribution only",
        "75% student impact, 15% mentor, 10% compute",
        "50% platform fee, 50% students",
        "100% sponsor refund on failure"
      ],
      correct: 1
    }
  ];

  const handleOptionSelect = (qId, optIdx) => {
    if (submitted) return;
    setSelectedAnswers(prev => ({ ...prev, [qId]: optIdx }));
  };

  const handleSubmitTest = (e) => {
    e.preventDefault();
    let correctCount = 0;
    questions.forEach(q => {
      if (selectedAnswers[q.id] === q.correct) correctCount++;
    });
    const finalScore = Math.round((correctCount / questions.length) * 100);
    setScore(finalScore);
    setSubmitted(true);

    if (onAddLedgerEntry) {
      onAddLedgerEntry({
        action: 'DEMO_TEST_SUBMITTED',
        actor: 'Student (Team Alpha)',
        hash: '0x' + Math.random().toString(16).slice(2, 12) + 'dt55'
      });
    }
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <Award className="text-emerald-400 w-6 h-6" />
          Milestone Demo & AI Evaluation Test
        </h2>
        <p className="text-gray-400 text-sm mt-1">
          Automated evaluation challenge generated by the upper AI gateway to verify technical competency[cite: 9, 10].
        </p>
      </div>

      <div className="bg-[#09090b] border border-gray-800 rounded-xl p-8 shadow-xl space-y-6">
        {!submitted ? (
          <form onSubmit={handleSubmitTest} className="space-y-6">
            {questions.map((q, qIdx) => (
              <div key={q.id} className="space-y-3 pb-4 border-b border-gray-900 last:border-none">
                <div className="text-sm font-semibold text-white flex items-center gap-2">
                  <HelpCircle className="w-4 h-4 text-emerald-400" />
                  Q{qIdx + 1}. {q.question}
                </div>
                <div className="space-y-2 pl-6">
                  {q.options.map((opt, optIdx) => (
                    <label key={optIdx} className="flex items-center gap-3 text-xs font-mono text-gray-300 cursor-pointer p-2 rounded hover:bg-gray-900/40 transition">
                      <input
                        type="radio"
                        name={`question-${q.id}`}
                        checked={selectedAnswers[q.id] === optIdx}
                        onChange={() => handleOptionSelect(q.id, optIdx)}
                        className="accent-emerald-500"
                      />
                      {opt}
                    </label>
                  ))}
                </div>
              </div>
            ))}

            <button
              type="submit"
              className="w-full bg-emerald-600 hover:bg-emerald-500 text-black font-semibold py-3 rounded-lg text-sm transition font-mono flex items-center justify-center gap-2 shadow-[0_0_20px_rgba(16,185,129,0.2)]"
            >
              <Send className="w-4 h-4" /> Submit Milestone Test
            </button>
          </form>
        ) : (
          <div className="space-y-6 text-center py-6">
            <div className="w-16 h-16 rounded-full bg-emerald-950/40 border border-emerald-500/40 flex items-center justify-center mx-auto text-emerald-400">
              <CheckCircle2 className="w-8 h-8" />
            </div>
            <div className="space-y-2">
              <h3 className="text-xl font-bold text-white">Evaluation Complete</h3>
              <p className="text-sm font-mono text-emerald-400">Achieved Score: {score}% — Verified on Live Ledger</p>
            </div>
            <button
              onClick={() => { setSubmitted(false); setSelectedAnswers({}); }}
              className="bg-gray-900 border border-gray-800 text-gray-300 hover:text-white px-6 py-2.5 rounded-lg text-xs font-mono transition"
            >
              Retake Test
            </button>
          </div>
        )}
      </div>
    </div>
  );
}